@baseUri=https://localhost:52095/api/v1

POST {{baseUri}}/authentication/sign-up
Content-Type: application/json

{
    "username": "test@test.com",
    "password": "P@ssw0rd"
}

###

POST {{baseUri}}/authentication/sign-in
Content-Type: application/json

{
    "username": "test@test.com",
    "password": "P@ssw0rd"
}

###

GET {{baseUri}}/user-management/users?pageNumber=1&pageSize=10

###

GET {{baseUri}}/user-management/users?pageNumber=1&pageSize=10&username=John%20Doe