version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}filescollabweb
    build:
      context: .
      dockerfile: src/FilesCollab.Web/Dockerfile
    environment:
      - SqlServer__ConnectionString=Server=sqlserver,1433;Database=FilesCollab;User=sa;Password=P@ssw0rd;TrustServerCertificate=true;
    networks:
      - database
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"
    networks:
      database:
        aliases:
          - sqlserver
networks:
  database: