// <auto-generated />
using System;
using FilesCollab.Web.Dependencies.SqlServer.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilesCollab.Web.Dependencies.SqlServer.Application.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240222105353_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d058f91-a45f-4059-bbf5-0581973d902d"),
                            Name = "Administator"
                        });
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workspace");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Group", b =>
                {
                    b.HasOne("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Group", null)
                        .WithMany("Groups")
                        .HasForeignKey("GroupId");

                    b.HasOne("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Role", null)
                        .WithMany("Groups")
                        .HasForeignKey("RoleId");

                    b.HasOne("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Workspace", null)
                        .WithMany("Groups")
                        .HasForeignKey("WorkspaceId");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.User", b =>
                {
                    b.HasOne("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Group", null)
                        .WithMany("Users")
                        .HasForeignKey("GroupId");

                    b.HasOne("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Workspace", null)
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Group", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Role", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FilesCollab.Web.Dependencies.SqlServer.Application.Entities.Workspace", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
